
# Download bcl2fastq

- name: Download and unpack bcl2fastq
  block:
    - name: Download bcl2fastq
      get_url:
        url: ftp://webdata2:webdata2@ussd-ftp.illumina.com/downloads/software/bcl2fastq/bcl2fastq2-v{{version}}-tar.zip
        dest: "{{source_dir}}/bcl2fastq-{{version}}.zip"
    - name: Unpack1
      unarchive: 
        src: "{{ source_dir }}/bcl2fastq-{{version}}.zip"
        dest: "{{ source_dir }}"
        copy: no
        creates: "{{ source_dir }}/bcl2fastq2-v{{version}}.403.tar.gz"
    - name: Unpack2
      unarchive: 
        src: "{{ source_dir }}/bcl2fastq2-v{{version}}.403.tar.gz"
        dest: "{{ source_dir }}"
        copy: no
        creates: "{{ source_dir }}/bcl2fastq"
  become: yes
  become_user: "{{ ngs_user }}"


# Install libboost1.58

- name: Install libboost 1.58
  block:
    - apt: update_cache=yes cache_valid_time=3600
    - apt: pkg=libboost-all-dev state=present
    # Link stat.h header where bcl2fastq expects it
    - file: path=/usr/include/sys state=directory mode=u+w,a+rx
    - file: path=/usr/include/sys/stat.h state=link src=/usr/include/x86_64-linux-gnu/sys/stat.h


# Create build dir and configure

- file: path="{{ source_dir }}/bcl2fastq-build" state=directory mode=ug+rwx owner="{{ username }}" group="{{ username }}"

- name: Configure the build
  command: "{{ source_dir }}/bcl2fastq/src/configure --prefix={{ soft_dir }}/bcl2fastq-{{ version }}"
  args: 
    chdir: "{{ source_dir }}/bcl2fastq-build"
  become: yes
  become_user: "{{ ngs_user }}"

 
# Uninstall libboost1.58 and install libboost1.54 to make XML libraries
 
- name: Swicth libboost1.58 with 1.54
  block:
    - apt: pkg=libboost-all-dev state=absent autoremove=yes
    - name: add repo
      apt_repository:
        repo: deb http://archive.ubuntu.com/ubuntu trusty main restricted universe multiverse
        state: present
    - apt: pkg=libboost1.54-dev state=present


# make IO libs

- name: Make IO target
  command: make bcl2fastq_io chdir="{{ source_dir }}/bcl2fastq-build"
  become: yes
  become_user: "{{ ngs_user }}"


# Uninstall libboost1.54 and install 1.58 to continue the build

- name: Swich libboost 1.54 with 1.58
  block:
    - apt: pkg=libboost1.54-dev state=absent autoremove=yes
    - apt: pkg=libboost-all-dev state=present


# Continue building

- name: Make all
  block:
    - command: make chdir="{{ source_dir }}/bcl2fastq-build"
    - command: make install chdir="{{ source_dir }}/bcl2fastq-build"
  become: yes
  become_user: "{{ ngs_user }}"    

# Cleanup after the build

- name: Remove trusty repo
  apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu trusty main restricted universe multiverse
    state: absent
  
  
#- name: CHMOD the install dir
#  file: path={{ soft_dir }}/bcl2fastq-{{ version }} owner={{ username }} group={{ username }} recursive=yes

#- name: Cleanup build dirs
#  file: path="{{ item }}" state=absent
#  with_items:
#    - "{{ soft_dir }}/bcl2fastq"
#    - "{{ soft_dir }}/bcl2fastq-build"
