# Install dependencies

- name: Install dependencies 
  block:
  - apt: update_cache=yes cache_valid_time=3600
  - apt: pkg={{item}} state=present
    with_items:
      - python-ruffus
      - python-drmaa
      - slurm-drmaa1
  

# Set up env variable from SLURM-DRMAA
- name: set DRMAA_LIBRARY_PATH env variable
  lineinfile:
      path: /etc/environment
      line: 'export DRMAA_LIBRARY_PATH=/usr/lib/slurm-drmaa/lib/libdrmaa.so.1'
      create: yes
      

# Clone pipeline repo
- name: Clone pipeline 
  git:
    repo: "{{ repo }}"
    dest: "{{ soft_dir }}/bia-pipeline"
    version: "{{ version }}"
  become: yes
  become_user: "{{ ngs_user }}"



