
- name: Download and install VCFtools
  block:
  
    - name: Download vcftools
      get_url:
        url=https://github.com/vcftools/vcftools/releases/download/v{{ version }}/vcftools-{{ version }}.tar.gz
        dest={{source_dir}}/vcftools-{{version}}.tar.gz

    - name: Uncompress vcftools
      unarchive: 
        src: "{{ source_dir }}/vcftools-{{version}}.tar.gz"
        dest: "{{ source_dir }}"
        copy: no
        creates: "{{ source_dir }}/vcftools-{{version}}/README.txt"

    - name: Build and Install vcftools
      shell: cd {{ source_dir }}/vcftools-{{version}}; ./configure --prefix="{{ soft_dir }}/vcftools-{{version}}" && make && make install
      args:
        creates: "{{ soft_dir }}/vcftools-{{version}}/bin/vcftools"

  become: yes
  become_user: "{{ ngs_user }}"



#- file: dest="{{modules_dir}}/bio/vcftools" state=directory mode=0755

#- name: vcftools module definition
#  template:
#    src: templates/sw-module.lua.j2
#    dest: "{{ modules_dir }}/bio/vcftools/{{version}}.lua"
#    owner: root
#    mode: 0644
#  with_items:
#    - dir: 'vcftools_{{version}}' 
#      perl_path: 'lib/perl5/site_perl'
#      help_text: >
#        This module loads the vcftools tool suite

